#!C:/Users/sharm/AppData/Local/Programs/Python/Python38/python
print("Content-Type: text/html")
print()
import cgi
print("<h1>Thanks for Placing Your Order</h1>")
print("<hr>")
form=cgi.FieldStorage()
fname = form.getvalue("fname")
lname = form.getvalue("lname")
email = form.getvalue("email")
contact = form.getvalue("contact")
NS = form.getvalue("NS")
qty = form.getvalue("qty")
card = form.getvalue("card")
ccn=form.getvalue("ccn")
cvv=form.getvalue("cvv")
exp=form.getvalue("exp")
import mysql.connector
con=mysql.connector.connect(user='root',password='',host='localhost',database='demo')
cur=con.cursor()
cur.execute("insert into customers values(%s,%s,%s,%s)",(fname,lname,email,contact))
con.commit()
cur.close()
print('<p style="fontsize: large; color:green">Have a Good Day Visit Us Again!</p>')